// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Chaos.Infraestructure.Models;

public partial class ActiveDrinkEffect
{
    public Guid Id { get; set; }

    public Guid UserId { get; set; }

    public string EffectType { get; set; }

    public int RoundsRemaining { get; set; }

    public string CreatedAt { get; set; }

    public virtual User User { get; set; }
}