// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Chaos.Infraestructure.Models;

public partial class AnimalValueConfig
{
    public Guid Id { get; set; }

    public string AnimalType { get; set; }

    public int MinAge { get; set; }

    public int MaxAge { get; set; }

    public decimal MinWeight { get; set; }

    public decimal MaxWeight { get; set; }

    public decimal MinHeight { get; set; }

    public decimal MaxHeight { get; set; }

    public int MinHealth { get; set; }

    public int MaxHealth { get; set; }

    public string Habitat { get; set; }

    public string ImageUrlMecha { get; set; }

    public string ImageUrlNormal { get; set; }

    public bool IsActive { get; set; }

    public Guid? UpdatedBy { get; set; }

    public virtual ICollection<Animal> Animals { get; set; } = new List<Animal>();

    public virtual User UpdatedByNavigation { get; set; }
}