// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Chaos.Infraestructure.Models;

public partial class AnimalShop
{
    public Guid Id { get; set; }

    public string ShopName { get; set; }

    public string Description { get; set; }

    public string CreatedAt { get; set; }

    public virtual ICollection<ShopAnimalListing> ShopAnimalListings { get; set; } = new List<ShopAnimalListing>();
}