// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Reflection.Metadata;

namespace Chaos.Infraestructure.Models;

public partial class Animal
{
    public Guid Id { get; set; }

    public string Name { get; set; }

    public string AnimalType { get; set; }

    public bool Rarity { get; set; }

    public int Health { get; set; }

    public int? Age { get; set; }

    public decimal? Weight { get; set; }

    public decimal? Height { get; set; }

    public decimal EstimatedValue { get; set; }

    public bool IsAvailable { get; set; }

    public Guid? OwnerId { get; set; }

    public Guid? AnimalValueConfigId { get; set; }

    public string CreatedAt { get; set; }

    public virtual AnimalValueConfig AnimalValueConfig { get; set; }

    public virtual ICollection<BlackjackSession> BlackjackSessions { get; set; } = new List<BlackjackSession>();

    public virtual ICollection<CoinFlipSession> CoinFlipSessions { get; set; } = new List<CoinFlipSession>();

    public virtual ICollection<GameSession> GameSessions { get; set; } = new List<GameSession>();

    public virtual ICollection<HigherLowerSession> HigherLowerSessions { get; set; } = new List<HigherLowerSession>();

    public virtual User Owner { get; set; }

    public virtual ICollection<ShopAnimalListing> ShopAnimalListings { get; set; } = new List<ShopAnimalListing>();

    public virtual ICollection<ShopTransaction> ShopTransactions { get; set; } = new List<ShopTransaction>();
}