// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Chaos.Infraestructure.Models;

public partial class BlackjackSession
{
    public Guid Id { get; set; }

    public string Status { get; set; }

    public int PlayerScore { get; set; }

    public int DealerScore { get; set; }

    public bool HasSplit { get; set; }

    public bool HasDoubledDown { get; set; }

    public bool HasInsurance { get; set; }

    public bool? InsuranceWon { get; set; }

    public decimal MoneyEarned { get; set; }

    public string StartedAt { get; set; }

    public string FinishedAt { get; set; }

    public Guid UserId { get; set; }

    public Guid AnimalId { get; set; }

    public Guid GameSessionId { get; set; }

    public Guid BlackjackGameConfigId { get; set; }

    public virtual Animal Animal { get; set; }

    public virtual ICollection<BlackjackAction> BlackjackActions { get; set; } = new List<BlackjackAction>();

    public virtual BlackjackGameConfig BlackjackGameConfig { get; set; }

    public virtual ICollection<BlackjackHand> BlackjackHands { get; set; } = new List<BlackjackHand>();

    public virtual GameSession GameSession { get; set; }

    public virtual User User { get; set; }
}