// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Chaos.Infraestructure.Models;

public partial class BlackjackAction
{
    public Guid Id { get; set; }

    public string ActionType { get; set; }

    public int ActionOrder { get; set; }

    public string ActionAt { get; set; }

    public Guid BlackjackSessionId { get; set; }

    public Guid HandId { get; set; }

    public virtual BlackjackSession BlackjackSession { get; set; }

    public virtual BlackjackHand Hand { get; set; }
}