// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Chaos.Infraestructure.Models;

public partial class BlackjackCard
{
    public Guid Id { get; set; }

    public string CardValue { get; set; }

    public string CardSuit { get; set; }

    public string CardDisplay { get; set; }

    public int NumericValue { get; set; }

    public bool IsFaceDown { get; set; }

    public int DealtAt { get; set; }

    public int CardBlackjackValue { get; set; }

    public Guid HandId { get; set; }

    public virtual BlackjackHand Hand { get; set; }
}