// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Chaos.Infraestructure.Models;

public partial class BlackjackGameConfig
{
    public Guid Id { get; set; }

    public string TableName { get; set; }

    public int MaxPlayers { get; set; }

    public int NumberOfDecks { get; set; }

    public int DealerStandsOn { get; set; }

    public decimal BlackjackPayout { get; set; }

    public bool AllowDoubleDown { get; set; }

    public bool AllowInsurance { get; set; }

    public bool IsActive { get; set; }

    public string CreatedAt { get; set; }

    public Guid GameId { get; set; }

    public virtual ICollection<BlackjackSession> BlackjackSessions { get; set; } = new List<BlackjackSession>();

    public virtual Game Game { get; set; }
}