// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Chaos.Infraestructure.Models;

public partial class BlackjackHand
{
    public Guid Id { get; set; }

    public string HandOwner { get; set; }

    public int HandNumber { get; set; }

    public int FinalScore { get; set; }

    public bool IsBust { get; set; }

    public bool IsBlackjack { get; set; }

    public Guid BlackjackSessionId { get; set; }

    public virtual ICollection<BlackjackAction> BlackjackActions { get; set; } = new List<BlackjackAction>();

    public virtual ICollection<BlackjackCard> BlackjackCards { get; set; } = new List<BlackjackCard>();

    public virtual BlackjackSession BlackjackSession { get; set; }
}