// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Chaos.Infraestructure.Models;

public partial class CasinoDBContext : DbContext
{
    public CasinoDBContext(DbContextOptions<CasinoDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<ActiveDrinkEffect> ActiveDrinkEffects { get; set; }

    public virtual DbSet<Animal> Animals { get; set; }

    public virtual DbSet<AnimalShop> AnimalShops { get; set; }

    public virtual DbSet<AnimalValueConfig> AnimalValueConfigs { get; set; }

    public virtual DbSet<BlackjackAction> BlackjackActions { get; set; }

    public virtual DbSet<BlackjackCard> BlackjackCards { get; set; }

    public virtual DbSet<BlackjackGameConfig> BlackjackGameConfigs { get; set; }

    public virtual DbSet<BlackjackHand> BlackjackHands { get; set; }

    public virtual DbSet<BlackjackSession> BlackjackSessions { get; set; }

    public virtual DbSet<Casino> Casinos { get; set; }

    public virtual DbSet<CoinFlipGameConfig> CoinFlipGameConfigs { get; set; }

    public virtual DbSet<CoinFlipSession> CoinFlipSessions { get; set; }

    public virtual DbSet<Game> Games { get; set; }

    public virtual DbSet<GameSession> GameSessions { get; set; }

    public virtual DbSet<HigherLowerGameConfig> HigherLowerGameConfigs { get; set; }

    public virtual DbSet<HigherLowerRound> HigherLowerRounds { get; set; }

    public virtual DbSet<HigherLowerSession> HigherLowerSessions { get; set; }

    public virtual DbSet<RouletteBetType> RouletteBetTypes { get; set; }

    public virtual DbSet<RouletteGameConfig> RouletteGameConfigs { get; set; }

    public virtual DbSet<RouletteSession> RouletteSessions { get; set; }

    public virtual DbSet<RussianRouletteGameConfig> RussianRouletteGameConfigs { get; set; }

    public virtual DbSet<RussianRouletteLobby> RussianRouletteLobbies { get; set; }

    public virtual DbSet<RussianRoulettePlayer> RussianRoulettePlayers { get; set; }

    public virtual DbSet<RussianRouletteRound> RussianRouletteRounds { get; set; }

    public virtual DbSet<ShopAnimalListing> ShopAnimalListings { get; set; }

    public virtual DbSet<ShopTransaction> ShopTransactions { get; set; }

    public virtual DbSet<SlotGameConfig> SlotGameConfigs { get; set; }

    public virtual DbSet<SlotPayoutRule> SlotPayoutRules { get; set; }

    public virtual DbSet<SlotSession> SlotSessions { get; set; }

    public virtual DbSet<SlotSymbol> SlotSymbols { get; set; }

    public virtual DbSet<User> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<ActiveDrinkEffect>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.CreatedAt).HasMaxLength(50);
            entity.Property(e => e.EffectType)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.User).WithMany(p => p.ActiveDrinkEffects)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_ActiveDrinkEffects_Users");
        });

        modelBuilder.Entity<Animal>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.AnimalType)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.CreatedAt).HasMaxLength(50);
            entity.Property(e => e.EstimatedValue).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Health).HasDefaultValue(100);
            entity.Property(e => e.Height).HasColumnType("decimal(8, 2)");
            entity.Property(e => e.IsAvailable).HasDefaultValue(true);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Weight).HasColumnType("decimal(8, 2)");

            entity.HasOne(d => d.AnimalValueConfig).WithMany(p => p.Animals)
                .HasForeignKey(d => d.AnimalValueConfigId)
                .HasConstraintName("FK_Animals_ValueConfig");

            entity.HasOne(d => d.Owner).WithMany(p => p.Animals)
                .HasForeignKey(d => d.OwnerId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK_Animals_Users");
        });

        modelBuilder.Entity<AnimalShop>(entity =>
        {
            entity.ToTable("AnimalShop");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.CreatedAt).HasMaxLength(50);
            entity.Property(e => e.Description).HasMaxLength(500);
            entity.Property(e => e.ShopName)
                .IsRequired()
                .HasMaxLength(150);
        });

        modelBuilder.Entity<AnimalValueConfig>(entity =>
        {
            entity.ToTable("AnimalValueConfig");

            entity.HasIndex(e => e.AnimalType, "IX_AnimalValueConfig_AnimalType").IsUnique();

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.AnimalType)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Habitat)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.ImageUrlMecha).HasColumnType("text");
            entity.Property(e => e.ImageUrlNormal).HasColumnType("text");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.MaxHeight).HasColumnType("decimal(8, 2)");
            entity.Property(e => e.MaxWeight).HasColumnType("decimal(8, 2)");
            entity.Property(e => e.MinHeight).HasColumnType("decimal(8, 2)");
            entity.Property(e => e.MinWeight).HasColumnType("decimal(8, 2)");

            entity.HasOne(d => d.UpdatedByNavigation).WithMany(p => p.AnimalValueConfigs)
                .HasForeignKey(d => d.UpdatedBy)
                .HasConstraintName("FK_AnimalValueConfig_Users");
        });

        modelBuilder.Entity<BlackjackAction>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.ActionAt).HasMaxLength(50);
            entity.Property(e => e.ActionType)
                .IsRequired()
                .HasMaxLength(15);

            entity.HasOne(d => d.BlackjackSession).WithMany(p => p.BlackjackActions)
                .HasForeignKey(d => d.BlackjackSessionId)
                .HasConstraintName("FK_BJActions_Sessions");

            entity.HasOne(d => d.Hand).WithMany(p => p.BlackjackActions)
                .HasForeignKey(d => d.HandId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BJActions_Hands");
        });

        modelBuilder.Entity<BlackjackCard>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.CardDisplay)
                .IsRequired()
                .HasMaxLength(10);
            entity.Property(e => e.CardSuit)
                .IsRequired()
                .HasMaxLength(10);
            entity.Property(e => e.CardValue)
                .IsRequired()
                .HasMaxLength(5);

            entity.HasOne(d => d.Hand).WithMany(p => p.BlackjackCards)
                .HasForeignKey(d => d.HandId)
                .HasConstraintName("FK_BJCards_Hands");
        });

        modelBuilder.Entity<BlackjackGameConfig>(entity =>
        {
            entity.ToTable("BlackjackGameConfig");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.AllowDoubleDown).HasDefaultValue(true);
            entity.Property(e => e.AllowInsurance).HasDefaultValue(true);
            entity.Property(e => e.BlackjackPayout)
                .HasDefaultValue(1.50m)
                .HasColumnType("decimal(4, 2)");
            entity.Property(e => e.CreatedAt).HasMaxLength(50);
            entity.Property(e => e.DealerStandsOn).HasDefaultValue(17);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.MaxPlayers).HasDefaultValue(6);
            entity.Property(e => e.NumberOfDecks).HasDefaultValue(6);
            entity.Property(e => e.TableName)
                .IsRequired()
                .HasMaxLength(100);

            entity.HasOne(d => d.Game).WithMany(p => p.BlackjackGameConfigs)
                .HasForeignKey(d => d.GameId)
                .HasConstraintName("FK_BlackjackGameConfig_Games");
        });

        modelBuilder.Entity<BlackjackHand>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.HandNumber).HasDefaultValue(1);
            entity.Property(e => e.HandOwner)
                .IsRequired()
                .HasMaxLength(10);

            entity.HasOne(d => d.BlackjackSession).WithMany(p => p.BlackjackHands)
                .HasForeignKey(d => d.BlackjackSessionId)
                .HasConstraintName("FK_BJHands_Sessions");
        });

        modelBuilder.Entity<BlackjackSession>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.FinishedAt).HasMaxLength(50);
            entity.Property(e => e.MoneyEarned).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.StartedAt).HasMaxLength(50);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("InProgress");

            entity.HasOne(d => d.Animal).WithMany(p => p.BlackjackSessions)
                .HasForeignKey(d => d.AnimalId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BJSessions_Animals");

            entity.HasOne(d => d.BlackjackGameConfig).WithMany(p => p.BlackjackSessions)
                .HasForeignKey(d => d.BlackjackGameConfigId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BJSessions_GameConfig");

            entity.HasOne(d => d.GameSession).WithMany(p => p.BlackjackSessions)
                .HasForeignKey(d => d.GameSessionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BJSessions_GameSessions");

            entity.HasOne(d => d.User).WithMany(p => p.BlackjackSessions)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BJSessions_Users");
        });

        modelBuilder.Entity<Casino>(entity =>
        {
            entity.ToTable("Casino");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.CreatedAt).HasMaxLength(50);
            entity.Property(e => e.Description).HasMaxLength(500);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(150);
        });

        modelBuilder.Entity<CoinFlipGameConfig>(entity =>
        {
            entity.ToTable("CoinFlipGameConfig");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.ConfigName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.CreatedAt).HasMaxLength(50);
            entity.Property(e => e.IsActive).HasDefaultValue(true);

            entity.HasOne(d => d.Game).WithMany(p => p.CoinFlipGameConfigs)
                .HasForeignKey(d => d.GameId)
                .HasConstraintName("FK_CoinFlipGameConfig_Games");
        });

        modelBuilder.Entity<CoinFlipSession>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.CoinResult)
                .IsRequired()
                .HasMaxLength(10);
            entity.Property(e => e.MoneyEarned).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.PlayedAt).HasMaxLength(50);
            entity.Property(e => e.PrizeMultiplierUsed).HasColumnType("decimal(8, 2)");
            entity.Property(e => e.UserChoice)
                .IsRequired()
                .HasMaxLength(10);
            entity.Property(e => e.WinProbabilityUsed).HasColumnType("decimal(5, 2)");

            entity.HasOne(d => d.Animal).WithMany(p => p.CoinFlipSessions)
                .HasForeignKey(d => d.AnimalId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CFSessions_Animals");

            entity.HasOne(d => d.CoinFlipGameConfig).WithMany(p => p.CoinFlipSessions)
                .HasForeignKey(d => d.CoinFlipGameConfigId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CFSessions_GameConfig");

            entity.HasOne(d => d.GameSession).WithMany(p => p.CoinFlipSessions)
                .HasForeignKey(d => d.GameSessionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CFSessions_GameSessions");

            entity.HasOne(d => d.User).WithMany(p => p.CoinFlipSessions)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CFSessions_Users");
        });

        modelBuilder.Entity<Game>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.CreatedAt).HasMaxLength(50);
            entity.Property(e => e.Description).HasMaxLength(500);
            entity.Property(e => e.GameName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.GameType)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
        });

        modelBuilder.Entity<GameSession>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.MoneyEarned).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Multiplier)
                .HasDefaultValue(1.00m)
                .HasColumnType("decimal(8, 2)");
            entity.Property(e => e.PlayedAt).HasMaxLength(50);
            entity.Property(e => e.Result)
                .IsRequired()
                .HasMaxLength(10);

            entity.HasOne(d => d.Animal).WithMany(p => p.GameSessions)
                .HasForeignKey(d => d.AnimalId)
                .HasConstraintName("FK_GameSessions_Animals");

            entity.HasOne(d => d.Game).WithMany(p => p.GameSessions)
                .HasForeignKey(d => d.GameId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_GameSessions_Games");

            entity.HasOne(d => d.User).WithMany(p => p.GameSessions)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_GameSessions_Users");
        });

        modelBuilder.Entity<HigherLowerGameConfig>(entity =>
        {
            entity.ToTable("HigherLowerGameConfig");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.BaseMultiplier)
                .HasDefaultValue(1.00m)
                .HasColumnType("decimal(8, 2)");
            entity.Property(e => e.ConfigName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.CreatedAt).HasMaxLength(50);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.RoundIncrement)
                .HasDefaultValue(0.50m)
                .HasColumnType("decimal(8, 2)");

            entity.HasOne(d => d.Game).WithMany(p => p.HigherLowerGameConfigs)
                .HasForeignKey(d => d.GameId)
                .HasConstraintName("FK_HigherLowerGameConfig_Games");
        });

        modelBuilder.Entity<HigherLowerRound>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.CurrentCard)
                .IsRequired()
                .HasMaxLength(10);
            entity.Property(e => e.EarnedThisRound).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.NextCard).HasMaxLength(10);
            entity.Property(e => e.PlayedAt).HasMaxLength(50);
            entity.Property(e => e.UserGuess)
                .IsRequired()
                .HasMaxLength(10);

            entity.HasOne(d => d.HigherLowerSession).WithMany(p => p.HigherLowerRounds)
                .HasForeignKey(d => d.HigherLowerSessionId)
                .HasConstraintName("FK_HLRounds_HLSessions");
        });

        modelBuilder.Entity<HigherLowerSession>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.FinishedAt).HasMaxLength(50);
            entity.Property(e => e.StartedAt).HasMaxLength(50);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("InProgress");
            entity.Property(e => e.TotalEarned).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.Animal).WithMany(p => p.HigherLowerSessions)
                .HasForeignKey(d => d.AnimalId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_HLSessions_Animals");

            entity.HasOne(d => d.GameSession).WithMany(p => p.HigherLowerSessions)
                .HasForeignKey(d => d.GameSessionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_HLSessions_GameSessions");

            entity.HasOne(d => d.HigherLowerGameConfig).WithMany(p => p.HigherLowerSessions)
                .HasForeignKey(d => d.HigherLowerGameConfigId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_HLSessions_GameConfig");

            entity.HasOne(d => d.User).WithMany(p => p.HigherLowerSessions)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_HLSessions_Users");
        });

        modelBuilder.Entity<RouletteBetType>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.BetName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.CreatedAt).HasMaxLength(50);
            entity.Property(e => e.Description).HasMaxLength(255);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.Payout).HasColumnType("decimal(8, 2)");

            entity.HasOne(d => d.RouletteGameConfig).WithMany(p => p.RouletteBetTypes)
                .HasForeignKey(d => d.RouletteGameConfigId)
                .HasConstraintName("FK_RouletteBetTypes_RouletteGameConfig");
        });

        modelBuilder.Entity<RouletteGameConfig>(entity =>
        {
            entity.ToTable("RouletteGameConfig");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.CreatedAt).HasMaxLength(50);
            entity.Property(e => e.HasZero).HasDefaultValue(true);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.RouletteType)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("European");
            entity.Property(e => e.TableName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.TotalNumbers).HasDefaultValue(37);

            entity.HasOne(d => d.Game).WithMany(p => p.RouletteGameConfigs)
                .HasForeignKey(d => d.GameId)
                .HasConstraintName("FK_RouletteGameConfig_Games");
        });

        modelBuilder.Entity<RouletteSession>(entity =>
        {
            entity.ToTable("RouletteSession");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.HasOne(d => d.GameSession).WithMany(p => p.RouletteSessions)
                .HasForeignKey(d => d.GameSessionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RouletteSession_GameSession");

            entity.HasOne(d => d.RouletteGameConfig).WithMany(p => p.RouletteSessions)
                .HasForeignKey(d => d.RouletteGameConfigId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RouletteSession_RouletteGameConfig");
        });

        modelBuilder.Entity<RussianRouletteGameConfig>(entity =>
        {
            entity.ToTable("RussianRouletteGameConfig");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.AllowBots).HasDefaultValue(true);
            entity.Property(e => e.BulletCount).HasDefaultValue(1);
            entity.Property(e => e.ConfigName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.CreatedAt).HasMaxLength(50);
            entity.Property(e => e.FixedPrizePool)
                .HasDefaultValue(500.00m)
                .HasColumnType("decimal(18, 2)");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.MaxPlayers).HasDefaultValue(6);
            entity.Property(e => e.MinPlayers).HasDefaultValue(2);
            entity.Property(e => e.TotalChambers).HasDefaultValue(6);

            entity.HasOne(d => d.Game).WithMany(p => p.RussianRouletteGameConfigs)
                .HasForeignKey(d => d.GameId)
                .HasConstraintName("FK_RussianRouletteGameConfig_Games");
        });

        modelBuilder.Entity<RussianRouletteLobby>(entity =>
        {
            entity.HasIndex(e => e.LobbyCode, "IX_RussianRouletteLobbies_LobbyCode").IsUnique();

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.CreatedAt).HasMaxLength(50);
            entity.Property(e => e.CurrentPrizePool).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.FinishedAt).HasMaxLength(50);
            entity.Property(e => e.LobbyCode)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.StartedAt).HasMaxLength(50);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("Waiting");

            entity.HasOne(d => d.GameSession).WithMany(p => p.RussianRouletteLobbies)
                .HasForeignKey(d => d.GameSessionId)
                .HasConstraintName("FK_RussianRouletteLobbies_GameSessions");

            entity.HasOne(d => d.RussianRouletteGameConfig).WithMany(p => p.RussianRouletteLobbies)
                .HasForeignKey(d => d.RussianRouletteGameConfigId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RRLobbies_GameConfig");

            entity.HasOne(d => d.Winner).WithMany(p => p.RussianRouletteLobbies)
                .HasForeignKey(d => d.WinnerId)
                .HasConstraintName("FK_RRLobbies_Winner");
        });

        modelBuilder.Entity<RussianRoulettePlayer>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.BotName).HasMaxLength(100);
            entity.Property(e => e.EliminatedAt).HasMaxLength(50);
            entity.Property(e => e.IsAlive).HasDefaultValue(true);
            entity.Property(e => e.JoinedAt).HasMaxLength(50);

            entity.HasOne(d => d.Lobby).WithMany(p => p.RussianRoulettePlayers)
                .HasForeignKey(d => d.LobbyId)
                .HasConstraintName("FK_RRPlayers_Lobbies");

            entity.HasOne(d => d.User).WithMany(p => p.RussianRoulettePlayers)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_RRPlayers_Users");
        });

        modelBuilder.Entity<RussianRouletteRound>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.PlayedAt).HasMaxLength(50);

            entity.HasOne(d => d.Lobby).WithMany(p => p.RussianRouletteRounds)
                .HasForeignKey(d => d.LobbyId)
                .HasConstraintName("FK_RRRounds_Lobbies");

            entity.HasOne(d => d.Player).WithMany(p => p.RussianRouletteRounds)
                .HasForeignKey(d => d.PlayerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RRRounds_Players");
        });

        modelBuilder.Entity<ShopAnimalListing>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.ListedAt).HasMaxLength(50);
            entity.Property(e => e.ListingPrice).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.SoldAt).HasMaxLength(50);

            entity.HasOne(d => d.Animal).WithMany(p => p.ShopAnimalListings)
                .HasForeignKey(d => d.AnimalId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Listings_Animals");

            entity.HasOne(d => d.AnimalShop).WithMany(p => p.ShopAnimalListings)
                .HasForeignKey(d => d.AnimalShopId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Listings_AnimalShop");
        });

        modelBuilder.Entity<ShopTransaction>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.TransactionDate).HasMaxLength(50);
            entity.Property(e => e.TransactionType)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.Animal).WithMany(p => p.ShopTransactions)
                .HasForeignKey(d => d.AnimalId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ShopTrans_Animals");

            entity.HasOne(d => d.User).WithMany(p => p.ShopTransactions)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ShopTrans_Users");
        });

        modelBuilder.Entity<SlotGameConfig>(entity =>
        {
            entity.ToTable("SlotGameConfig");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.CreatedAt).HasMaxLength(50);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.MachineName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Multiplier)
                .HasDefaultValue(1.00m)
                .HasColumnType("decimal(8, 2)");
            entity.Property(e => e.NumberOfReels).HasDefaultValue(3);
            entity.Property(e => e.NumberOfRows).HasDefaultValue(1);
            entity.Property(e => e.PayLines).HasDefaultValue(1);

            entity.HasOne(d => d.Game).WithMany(p => p.SlotGameConfigs)
                .HasForeignKey(d => d.GameId)
                .HasConstraintName("FK_SlotGameConfig_Games");
        });

        modelBuilder.Entity<SlotPayoutRule>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Combination)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.CreatedAt).HasMaxLength(50);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.PayoutMultiplier).HasColumnType("decimal(8, 2)");

            entity.HasOne(d => d.SlotGameConfig).WithMany(p => p.SlotPayoutRules)
                .HasForeignKey(d => d.SlotGameConfigId)
                .HasConstraintName("FK_PayoutRules_SlotGameConfig");

            entity.HasOne(d => d.SlotSymbol).WithMany(p => p.SlotPayoutRules)
                .HasForeignKey(d => d.SlotSymbolId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PayoutRules_SlotSymbols");
        });

        modelBuilder.Entity<SlotSession>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.BetAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.WinningSymbols).HasMaxLength(500);

            entity.HasOne(d => d.GameSession).WithMany(p => p.SlotSessions)
                .HasForeignKey(d => d.GameSessionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SlotSession_GameSessions");

            entity.HasOne(d => d.SlotGameConfig).WithMany(p => p.SlotSessions)
                .HasForeignKey(d => d.SlotGameConfigId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SlotSession_GameConfig");
        });

        modelBuilder.Entity<SlotSymbol>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.BaseValue)
                .HasDefaultValue(1.00m)
                .HasColumnType("decimal(8, 2)");
            entity.Property(e => e.CreatedAt).HasMaxLength(50);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.Rarity)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.SymbolCode)
                .IsRequired()
                .HasMaxLength(10);
            entity.Property(e => e.SymbolName)
                .IsRequired()
                .HasMaxLength(100);

            entity.HasOne(d => d.SlotGameConfig).WithMany(p => p.SlotSymbols)
                .HasForeignKey(d => d.SlotGameConfigId)
                .HasConstraintName("FK_SlotSymbols_SlotGameConfig");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasIndex(e => e.Email, "IX_Users_Email").IsUnique();

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.CreatedAt).HasMaxLength(50);
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.PasswordHash)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.Wallet).HasColumnType("decimal(18, 2)");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}