// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Chaos.Infraestructure.Models;

public partial class CoinFlipGameConfig
{
    public Guid Id { get; set; }

    public string ConfigName { get; set; }

    public bool IsActive { get; set; }

    public string CreatedAt { get; set; }

    public Guid GameId { get; set; }

    public virtual ICollection<CoinFlipSession> CoinFlipSessions { get; set; } = new List<CoinFlipSession>();

    public virtual Game Game { get; set; }
}