// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Chaos.Infraestructure.Models;

public partial class CoinFlipSession
{
    public Guid Id { get; set; }

    public string CoinResult { get; set; }

    public string UserChoice { get; set; }

    public bool IsWin { get; set; }

    public decimal WinProbabilityUsed { get; set; }

    public decimal PrizeMultiplierUsed { get; set; }

    public decimal MoneyEarned { get; set; }

    public string PlayedAt { get; set; }

    public Guid UserId { get; set; }

    public Guid AnimalId { get; set; }

    public Guid GameSessionId { get; set; }

    public Guid CoinFlipGameConfigId { get; set; }

    public virtual Animal Animal { get; set; }

    public virtual CoinFlipGameConfig CoinFlipGameConfig { get; set; }

    public virtual GameSession GameSession { get; set; }

    public virtual User User { get; set; }
}