// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Chaos.Infraestructure.Models;

public partial class Game
{
    public Guid Id { get; set; }

    public string GameName { get; set; }

    public string GameType { get; set; }

    public string Description { get; set; }

    public bool IsActive { get; set; }

    public string CreatedAt { get; set; }

    public virtual ICollection<BlackjackGameConfig> BlackjackGameConfigs { get; set; } = new List<BlackjackGameConfig>();

    public virtual ICollection<CoinFlipGameConfig> CoinFlipGameConfigs { get; set; } = new List<CoinFlipGameConfig>();

    public virtual ICollection<GameSession> GameSessions { get; set; } = new List<GameSession>();

    public virtual ICollection<HigherLowerGameConfig> HigherLowerGameConfigs { get; set; } = new List<HigherLowerGameConfig>();

    public virtual ICollection<RouletteGameConfig> RouletteGameConfigs { get; set; } = new List<RouletteGameConfig>();

    public virtual ICollection<RussianRouletteGameConfig> RussianRouletteGameConfigs { get; set; } = new List<RussianRouletteGameConfig>();

    public virtual ICollection<SlotGameConfig> SlotGameConfigs { get; set; } = new List<SlotGameConfig>();
}