// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Chaos.Infraestructure.Models;

public partial class GameSession
{
    public Guid Id { get; set; }

    public string Result { get; set; }

    public decimal MoneyEarned { get; set; }

    public decimal Multiplier { get; set; }

    public string PlayedAt { get; set; }

    public Guid UserId { get; set; }

    public Guid? AnimalId { get; set; }

    public Guid GameId { get; set; }

    public virtual Animal Animal { get; set; }

    public virtual ICollection<BlackjackSession> BlackjackSessions { get; set; } = new List<BlackjackSession>();

    public virtual ICollection<CoinFlipSession> CoinFlipSessions { get; set; } = new List<CoinFlipSession>();

    public virtual Game Game { get; set; }

    public virtual ICollection<HigherLowerSession> HigherLowerSessions { get; set; } = new List<HigherLowerSession>();

    public virtual ICollection<RouletteSession> RouletteSessions { get; set; } = new List<RouletteSession>();

    public virtual ICollection<RussianRouletteLobby> RussianRouletteLobbies { get; set; } = new List<RussianRouletteLobby>();

    public virtual ICollection<SlotSession> SlotSessions { get; set; } = new List<SlotSession>();

    public virtual User User { get; set; }
}