// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Chaos.Infraestructure.Models;

public partial class HigherLowerSession
{
    public Guid Id { get; set; }

    public string Status { get; set; }

    public decimal TotalEarned { get; set; }

    public int RoundsPlayed { get; set; }

    public string StartedAt { get; set; }

    public string FinishedAt { get; set; }

    public Guid UserId { get; set; }

    public Guid AnimalId { get; set; }

    public Guid GameSessionId { get; set; }

    public Guid HigherLowerGameConfigId { get; set; }

    public virtual Animal Animal { get; set; }

    public virtual GameSession GameSession { get; set; }

    public virtual HigherLowerGameConfig HigherLowerGameConfig { get; set; }

    public virtual ICollection<HigherLowerRound> HigherLowerRounds { get; set; } = new List<HigherLowerRound>();

    public virtual User User { get; set; }
}