// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Chaos.Infraestructure.Models;

public partial class HigherLowerGameConfig
{
    public Guid Id { get; set; }

    public string ConfigName { get; set; }

    public decimal BaseMultiplier { get; set; }

    public decimal RoundIncrement { get; set; }

    public bool IsActive { get; set; }

    public string CreatedAt { get; set; }

    public Guid GameId { get; set; }

    public virtual Game Game { get; set; }

    public virtual ICollection<HigherLowerSession> HigherLowerSessions { get; set; } = new List<HigherLowerSession>();
}