// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Chaos.Infraestructure.Models;

public partial class HigherLowerRound
{
    public Guid Id { get; set; }

    public int RoundNumber { get; set; }

    public string CurrentCard { get; set; }

    public string NextCard { get; set; }

    public string UserGuess { get; set; }

    public bool? IsCorrect { get; set; }

    public decimal EarnedThisRound { get; set; }

    public string PlayedAt { get; set; }

    public Guid HigherLowerSessionId { get; set; }

    public virtual HigherLowerSession HigherLowerSession { get; set; }
}