// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Chaos.Infraestructure.Models;

public partial class RouletteSession
{
    public Guid Id { get; set; }

    public int SpinResult { get; set; }

    public Guid RouletteGameConfigId { get; set; }

    public Guid GameSessionId { get; set; }

    public virtual GameSession GameSession { get; set; }

    public virtual RouletteGameConfig RouletteGameConfig { get; set; }
}