// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Chaos.Infraestructure.Models;

public partial class RouletteGameConfig
{
    public Guid Id { get; set; }

    public string TableName { get; set; }

    public string RouletteType { get; set; }

    public bool HasZero { get; set; }

    public bool HasDoubleZero { get; set; }

    public int TotalNumbers { get; set; }

    public bool IsActive { get; set; }

    public string CreatedAt { get; set; }

    public Guid GameId { get; set; }

    public virtual Game Game { get; set; }

    public virtual ICollection<RouletteBetType> RouletteBetTypes { get; set; } = new List<RouletteBetType>();

    public virtual ICollection<RouletteSession> RouletteSessions { get; set; } = new List<RouletteSession>();
}