// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Chaos.Infraestructure.Models;

public partial class RouletteBetType
{
    public Guid Id { get; set; }

    public string BetName { get; set; }

    public decimal Payout { get; set; }

    public string Description { get; set; }

    public bool IsActive { get; set; }

    public string CreatedAt { get; set; }

    public Guid RouletteGameConfigId { get; set; }

    public virtual RouletteGameConfig RouletteGameConfig { get; set; }
}