// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Chaos.Infraestructure.Models;

public partial class RussianRouletteRound
{
    public Guid Id { get; set; }

    public int RoundNumber { get; set; }

    public bool WasBullet { get; set; }

    public string PlayedAt { get; set; }

    public Guid LobbyId { get; set; }

    public Guid PlayerId { get; set; }

    public virtual RussianRouletteLobby Lobby { get; set; }

    public virtual RussianRoulettePlayer Player { get; set; }
}