// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Chaos.Infraestructure.Models;

public partial class RussianRoulettePlayer
{
    public Guid Id { get; set; }

    public bool IsBot { get; set; }

    public string BotName { get; set; }

    public int TurnOrder { get; set; }

    public bool IsAlive { get; set; }

    public bool IsWinner { get; set; }

    public string EliminatedAt { get; set; }

    public string JoinedAt { get; set; }

    public Guid? UserId { get; set; }

    public Guid LobbyId { get; set; }

    public virtual RussianRouletteLobby Lobby { get; set; }

    public virtual ICollection<RussianRouletteRound> RussianRouletteRounds { get; set; } = new List<RussianRouletteRound>();

    public virtual User User { get; set; }
}