// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Chaos.Infraestructure.Models;

public partial class RussianRouletteLobby
{
    public Guid Id { get; set; }

    public string LobbyCode { get; set; }

    public string Status { get; set; }

    public decimal CurrentPrizePool { get; set; }

    public Guid? WinnerId { get; set; }

    public string CreatedAt { get; set; }

    public string StartedAt { get; set; }

    public string FinishedAt { get; set; }

    public Guid? GameSessionId { get; set; }

    public Guid RussianRouletteGameConfigId { get; set; }

    public virtual GameSession GameSession { get; set; }

    public virtual RussianRouletteGameConfig RussianRouletteGameConfig { get; set; }

    public virtual ICollection<RussianRoulettePlayer> RussianRoulettePlayers { get; set; } = new List<RussianRoulettePlayer>();

    public virtual ICollection<RussianRouletteRound> RussianRouletteRounds { get; set; } = new List<RussianRouletteRound>();

    public virtual User Winner { get; set; }
}