// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Chaos.Infraestructure.Models;

public partial class RussianRouletteGameConfig
{
    public Guid Id { get; set; }

    public string ConfigName { get; set; }

    public int TotalChambers { get; set; }

    public int BulletCount { get; set; }

    public int MaxPlayers { get; set; }

    public int MinPlayers { get; set; }

    public decimal FixedPrizePool { get; set; }

    public bool AllowBots { get; set; }

    public bool IsActive { get; set; }

    public string CreatedAt { get; set; }

    public Guid GameId { get; set; }

    public virtual Game Game { get; set; }

    public virtual ICollection<RussianRouletteLobby> RussianRouletteLobbies { get; set; } = new List<RussianRouletteLobby>();
}