// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Chaos.Infraestructure.Models;

public partial class ShopTransaction
{
    public Guid Id { get; set; }

    public string TransactionType { get; set; }

    public decimal Amount { get; set; }

    public string TransactionDate { get; set; }

    public Guid UserId { get; set; }

    public Guid AnimalId { get; set; }

    public virtual Animal Animal { get; set; }

    public virtual User User { get; set; }
}