// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Chaos.Infraestructure.Models;

public partial class ShopAnimalListing
{
    public Guid Id { get; set; }

    public decimal ListingPrice { get; set; }

    public bool IsSold { get; set; }

    public string ListedAt { get; set; }

    public string SoldAt { get; set; }

    public Guid AnimalId { get; set; }

    public Guid AnimalShopId { get; set; }

    public virtual Animal Animal { get; set; }

    public virtual AnimalShop AnimalShop { get; set; }
}