// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Chaos.Infraestructure.Models;

public partial class SlotGameConfig
{
    public Guid Id { get; set; }

    public string MachineName { get; set; }

    public decimal Multiplier { get; set; }

    public int NumberOfReels { get; set; }

    public int NumberOfRows { get; set; }

    public int PayLines { get; set; }

    public bool IsActive { get; set; }

    public string CreatedAt { get; set; }

    public Guid GameId { get; set; }

    public virtual Game Game { get; set; }

    public virtual ICollection<SlotPayoutRule> SlotPayoutRules { get; set; } = new List<SlotPayoutRule>();

    public virtual ICollection<SlotSession> SlotSessions { get; set; } = new List<SlotSession>();

    public virtual ICollection<SlotSymbol> SlotSymbols { get; set; } = new List<SlotSymbol>();
}