// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Chaos.Infraestructure.Models;

public partial class SlotSession
{
    public Guid Id { get; set; }

    public decimal BetAmount { get; set; }

    public string WinningSymbols { get; set; }

    public Guid GameSessionId { get; set; }

    public Guid SlotGameConfigId { get; set; }

    public virtual GameSession GameSession { get; set; }

    public virtual SlotGameConfig SlotGameConfig { get; set; }
}