// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Chaos.Infraestructure.Models;

public partial class SlotPayoutRule
{
    public Guid Id { get; set; }

    public string Combination { get; set; }

    public decimal PayoutMultiplier { get; set; }

    public bool IsActive { get; set; }

    public string CreatedAt { get; set; }

    public Guid SlotGameConfigId { get; set; }

    public Guid SlotSymbolId { get; set; }

    public virtual SlotGameConfig SlotGameConfig { get; set; }

    public virtual SlotSymbol SlotSymbol { get; set; }
}