// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Chaos.Infraestructure.Models;

public partial class SlotSymbol
{
    public Guid Id { get; set; }

    public string SymbolName { get; set; }

    public string SymbolCode { get; set; }

    public string Rarity { get; set; }

    public decimal BaseValue { get; set; }

    public bool IsActive { get; set; }

    public string CreatedAt { get; set; }

    public Guid SlotGameConfigId { get; set; }

    public virtual SlotGameConfig SlotGameConfig { get; set; }

    public virtual ICollection<SlotPayoutRule> SlotPayoutRules { get; set; } = new List<SlotPayoutRule>();
}