// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Chaos.Infraestructure.Models;

public partial class User
{
    public Guid Id { get; set; }

    public string Name { get; set; }

    public string Email { get; set; }

    public string PasswordHash { get; set; }

    public decimal Wallet { get; set; }

    public string CreatedAt { get; set; }

    public bool IsActive { get; set; }

    public bool IsAdmin { get; set; }

    public virtual ICollection<ActiveDrinkEffect> ActiveDrinkEffects { get; set; } = new List<ActiveDrinkEffect>();

    public virtual ICollection<AnimalValueConfig> AnimalValueConfigs { get; set; } = new List<AnimalValueConfig>();

    public virtual ICollection<Animal> Animals { get; set; } = new List<Animal>();

    public virtual ICollection<BlackjackSession> BlackjackSessions { get; set; } = new List<BlackjackSession>();

    public virtual ICollection<CoinFlipSession> CoinFlipSessions { get; set; } = new List<CoinFlipSession>();

    public virtual ICollection<GameSession> GameSessions { get; set; } = new List<GameSession>();

    public virtual ICollection<HigherLowerSession> HigherLowerSessions { get; set; } = new List<HigherLowerSession>();

    public virtual ICollection<RussianRouletteLobby> RussianRouletteLobbies { get; set; } = new List<RussianRouletteLobby>();

    public virtual ICollection<RussianRoulettePlayer> RussianRoulettePlayers { get; set; } = new List<RussianRoulettePlayer>();

    public virtual ICollection<ShopTransaction> ShopTransactions { get; set; } = new List<ShopTransaction>();
}