// <auto-generated />
using System;
using Chaos.Infraestructure.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Chaos.Infraestructure.Migrations
{
    [DbContext(typeof(CasinoDBContext))]
    [Migration("20260602110238_AddCasinoSchema")]
    partial class AddCasinoSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Casino")
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Chaos.Infraestructure.Models.Animal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int?>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("AnimalType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("AnimalValueConfigId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedAt")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("EstimatedValue")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("Health")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(100);

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Rarity")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(8, 2)");

                    b.HasKey("Id");

                    b.HasIndex("AnimalValueConfigId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Animals", "Casino");
                });

            modelBuilder.Entity("Chaos.Infraestructure.Models.AnimalShop", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedAt")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ShopName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("AnimalShop", "Casino");
                });

            modelBuilder.Entity("Chaos.Infraestructure.Models.AnimalValueConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AnimalType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Habitat")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ImageUrlMecha")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrlNormal")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("MaxAge")
                        .HasColumnType("integer");

                    b.Property<int>("MaxHealth")
                        .HasColumnType("integer");

                    b.Property<decimal>("MaxHeight")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<decimal>("MaxWeight")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<int>("MinAge")
                        .HasColumnType("integer");

                    b.Property<int>("MinHealth")
                        .HasColumnType("integer");

                    b.Property<decimal>("MinHeight")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<decimal>("MinWeight")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedBy");

                    b.HasIndex(new[] { "AnimalType" }, "IX_AnimalValueConfig_AnimalType")
                        .IsUnique();

                    b.ToTable("AnimalValueConfig", "Casino");
                });

            modelBuilder.Entity("Chaos.Infraestructure.Models.BlackjackAction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ActionAt")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("ActionOrder")
                        .HasColumnType("integer");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<Guid>("BlackjackSessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("HandId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BlackjackSessionId");

                    b.HasIndex("HandId");

                    b.ToTable("BlackjackActions", "Casino");
                });

            modelBuilder.Entity("Chaos.Infraestructure.Models.BlackjackCard", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("CardBlackjackValue")
                        .HasColumnType("integer");

                    b.Property<string>("CardDisplay")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("CardSuit")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("CardValue")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<int>("DealtAt")
                        .HasColumnType("integer");

                    b.Property<Guid>("HandId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsFaceDown")
                        .HasColumnType("boolean");

                    b.Property<int>("NumericValue")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HandId");

                    b.ToTable("BlackjackCards", "Casino");
                });

            modelBuilder.Entity("Chaos.Infraestructure.Models.BlackjackGameConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowDoubleDown")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("AllowInsurance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<decimal>("BlackjackPayout")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(4, 2)")
                        .HasDefaultValue(1.50m);

                    b.Property<string>("CreatedAt")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("DealerStandsOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(17);

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("MaxPlayers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(6);

                    b.Property<int>("NumberOfDecks")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(6);

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("BlackjackGameConfig", "Casino");
                });

            modelBuilder.Entity("Chaos.Infraestructure.Models.BlackjackHand", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BlackjackSessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("FinalScore")
                        .HasColumnType("integer");

                    b.Property<int>("HandNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("HandOwner")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("IsBlackjack")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsBust")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("BlackjackSessionId");

                    b.ToTable("BlackjackHands", "Casino");
                });

            modelBuilder.Entity("Chaos.Infraestructure.Models.BlackjackSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnimalId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BlackjackGameConfigId")
                        .HasColumnType("uuid");

                    b.Property<int>("DealerScore")
                        .HasColumnType("integer");

                    b.Property<string>("FinishedAt")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("GameSessionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("HasDoubledDown")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasInsurance")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasSplit")
                        .HasColumnType("boolean");

                    b.Property<bool?>("InsuranceWon")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MoneyEarned")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("PlayerScore")
                        .HasColumnType("integer");

                    b.Property<string>("StartedAt")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("InProgress");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.HasIndex("BlackjackGameConfigId");

                    b.HasIndex("GameSessionId");

                    b.HasIndex("UserId");

                    b.ToTable("BlackjackSessions", "Casino");
                });

            modelBuilder.Entity("Chaos.Infraestructure.Models.Casino", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedAt")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("Casino", "Casino");
                });

            modelBuilder.Entity("Chaos.Infraestructure.Models.CoinFlipGameConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ConfigName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CreatedAt")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("CoinFlipGameConfig", "Casino");
                });

            modelBuilder.Entity("Chaos.Infraestructure.Models.CoinFlipSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnimalId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CoinFlipGameConfigId")
                        .HasColumnType("uuid");

                    b.Property<string>("CoinResult")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<Guid>("GameSessionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsWin")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MoneyEarned")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("PlayedAt")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("PrizeMultiplierUsed")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<string>("UserChoice")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("WinProbabilityUsed")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.HasIndex("CoinFlipGameConfigId");

                    b.HasIndex("GameSessionId");

                    b.HasIndex("UserId");

                    b.ToTable("CoinFlipSessions", "Casino");
                });

            modelBuilder.Entity("Chaos.Infraestructure.Models.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedAt")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("GameName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("GameType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.ToTable("Games", "Casino");
                });

            modelBuilder.Entity("Chaos.Infraestructure.Models.GameSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AnimalId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("MoneyEarned")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Multiplier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(8, 2)")
                        .HasDefaultValue(1.00m);

                    b.Property<string>("PlayedAt")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("GameSessions", "Casino");
                });

            modelBuilder.Entity("Chaos.Infraestructure.Models.HigherLowerGameConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("BaseMultiplier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(8, 2)")
                        .HasDefaultValue(1.00m);

                    b.Property<string>("ConfigName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CreatedAt")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<decimal>("RoundIncrement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(8, 2)")
                        .HasDefaultValue(0.50m);

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("HigherLowerGameConfig", "Casino");
                });

            modelBuilder.Entity("Chaos.Infraestructure.Models.HigherLowerRound", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CurrentCard")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal>("EarnedThisRound")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<Guid>("HigherLowerSessionId")
                        .HasColumnType("uuid");

                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<string>("NextCard")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("PlayedAt")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("integer");

                    b.Property<string>("UserGuess")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("HigherLowerSessionId");

                    b.ToTable("HigherLowerRounds", "Casino");
                });

            modelBuilder.Entity("Chaos.Infraestructure.Models.HigherLowerSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnimalId")
                        .HasColumnType("uuid");

                    b.Property<string>("FinishedAt")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("GameSessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("HigherLowerGameConfigId")
                        .HasColumnType("uuid");

                    b.Property<int>("RoundsPlayed")
                        .HasColumnType("integer");

                    b.Property<string>("StartedAt")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("InProgress");

                    b.Property<decimal>("TotalEarned")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.HasIndex("GameSessionId");

                    b.HasIndex("HigherLowerGameConfigId");

                    b.HasIndex("UserId");

                    b.ToTable("HigherLowerSessions", "Casino");
                });

            modelBuilder.Entity("Chaos.Infraestructure.Models.RouletteBetType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("BetName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CreatedAt")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<decimal>("Payout")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<Guid>("RouletteGameConfigId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RouletteGameConfigId");

                    b.ToTable("RouletteBetTypes", "Casino");
                });

            modelBuilder.Entity("Chaos.Infraestructure.Models.RouletteGameConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedAt")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<bool>("HasDoubleZero")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasZero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("RouletteType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("European");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("TotalNumbers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(37);

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("RouletteGameConfig", "Casino");
                });

            modelBuilder.Entity("Chaos.Infraestructure.Models.RouletteSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GameSessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RouletteGameConfigId")
                        .HasColumnType("uuid");

                    b.Property<int>("SpinResult")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameSessionId");

                    b.HasIndex("RouletteGameConfigId");

                    b.ToTable("RouletteSession", "Casino");
                });

            modelBuilder.Entity("Chaos.Infraestructure.Models.RussianRouletteGameConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowBots")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("BulletCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("ConfigName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CreatedAt")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("FixedPrizePool")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(500.00m);

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("MaxPlayers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(6);

                    b.Property<int>("MinPlayers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(2);

                    b.Property<int>("TotalChambers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(6);

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("RussianRouletteGameConfig", "Casino");
                });

            modelBuilder.Entity("Chaos.Infraestructure.Models.RussianRouletteLobby", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedAt")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("CurrentPrizePool")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("FinishedAt")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("GameSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("LobbyCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("RussianRouletteGameConfigId")
                        .HasColumnType("uuid");

                    b.Property<string>("StartedAt")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Waiting");

                    b.Property<Guid?>("WinnerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GameSessionId");

                    b.HasIndex("RussianRouletteGameConfigId");

                    b.HasIndex("WinnerId");

                    b.HasIndex(new[] { "LobbyCode" }, "IX_RussianRouletteLobbies_LobbyCode")
                        .IsUnique();

                    b.ToTable("RussianRouletteLobbies", "Casino");
                });

            modelBuilder.Entity("Chaos.Infraestructure.Models.RussianRoulettePlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("BotName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EliminatedAt")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsAlive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsBot")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsWinner")
                        .HasColumnType("boolean");

                    b.Property<string>("JoinedAt")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("LobbyId")
                        .HasColumnType("uuid");

                    b.Property<int>("TurnOrder")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LobbyId");

                    b.HasIndex("UserId");

                    b.ToTable("RussianRoulettePlayers", "Casino");
                });

            modelBuilder.Entity("Chaos.Infraestructure.Models.RussianRouletteRound", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LobbyId")
                        .HasColumnType("uuid");

                    b.Property<string>("PlayedAt")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("integer");

                    b.Property<bool>("WasBullet")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("LobbyId");

                    b.HasIndex("PlayerId");

                    b.ToTable("RussianRouletteRounds", "Casino");
                });

            modelBuilder.Entity("Chaos.Infraestructure.Models.ShopAnimalListing", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnimalId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnimalShopId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsSold")
                        .HasColumnType("boolean");

                    b.Property<string>("ListedAt")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("ListingPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("SoldAt")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.HasIndex("AnimalShopId");

                    b.ToTable("ShopAnimalListings", "Casino");
                });

            modelBuilder.Entity("Chaos.Infraestructure.Models.ShopTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<Guid>("AnimalId")
                        .HasColumnType("uuid");

                    b.Property<string>("TransactionDate")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.HasIndex("UserId");

                    b.ToTable("ShopTransactions", "Casino");
                });

            modelBuilder.Entity("Chaos.Infraestructure.Models.SlotGameConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedAt")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Multiplier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(8, 2)")
                        .HasDefaultValue(1.00m);

                    b.Property<int>("NumberOfReels")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3);

                    b.Property<int>("NumberOfRows")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int>("PayLines")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("SlotGameConfig", "Casino");
                });

            modelBuilder.Entity("Chaos.Infraestructure.Models.SlotPayoutRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Combination")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("CreatedAt")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<decimal>("PayoutMultiplier")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<Guid>("SlotGameConfigId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SlotSymbolId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SlotGameConfigId");

                    b.HasIndex("SlotSymbolId");

                    b.ToTable("SlotPayoutRules", "Casino");
                });

            modelBuilder.Entity("Chaos.Infraestructure.Models.SlotSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("BetAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<Guid>("GameSessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SlotGameConfigId")
                        .HasColumnType("uuid");

                    b.Property<string>("WinningSymbols")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("GameSessionId");

                    b.HasIndex("SlotGameConfigId");

                    b.ToTable("SlotSessions", "Casino");
                });

            modelBuilder.Entity("Chaos.Infraestructure.Models.SlotSymbol", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("BaseValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(8, 2)")
                        .HasDefaultValue(1.00m);

                    b.Property<string>("CreatedAt")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("SlotGameConfigId")
                        .HasColumnType("uuid");

                    b.Property<string>("SymbolCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("SymbolName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("SlotGameConfigId");

                    b.ToTable("SlotSymbols", "Casino");
                });

            modelBuilder.Entity("Chaos.Infraestructure.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedAt")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("Wallet")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Email" }, "IX_Users_Email")
                        .IsUnique();

                    b.ToTable("Users", "Casino");
                });

            modelBuilder.Entity("Chaos.Infraestructure.Models.Animal", b =>
                {
                    b.HasOne("Chaos.Infraestructure.Models.AnimalValueConfig", "AnimalValueConfig")
                        .WithMany("Animals")
                        .HasForeignKey("AnimalValueConfigId")
                        .HasConstraintName("FK_Animals_ValueConfig");

                    b.HasOne("Chaos.Infraestructure.Models.User", "Owner")
                        .WithMany("Animals")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Animals_Users");

                    b.Navigation("AnimalValueConfig");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Chaos.Infraestructure.Models.AnimalValueConfig", b =>
                {
                    b.HasOne("Chaos.Infraestructure.Models.User", "UpdatedByNavigation")
                        .WithMany("AnimalValueConfigs")
                        .HasForeignKey("UpdatedBy")
                        .HasConstraintName("FK_AnimalValueConfig_Users");

                    b.Navigation("UpdatedByNavigation");
                });

            modelBuilder.Entity("Chaos.Infraestructure.Models.BlackjackAction", b =>
                {
                    b.HasOne("Chaos.Infraestructure.Models.BlackjackSession", "BlackjackSession")
                        .WithMany("BlackjackActions")
                        .HasForeignKey("BlackjackSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_BJActions_Sessions");

                    b.HasOne("Chaos.Infraestructure.Models.BlackjackHand", "Hand")
                        .WithMany("BlackjackActions")
                        .HasForeignKey("HandId")
                        .IsRequired()
                        .HasConstraintName("FK_BJActions_Hands");

                    b.Navigation("BlackjackSession");

                    b.Navigation("Hand");
                });

            modelBuilder.Entity("Chaos.Infraestructure.Models.BlackjackCard", b =>
                {
                    b.HasOne("Chaos.Infraestructure.Models.BlackjackHand", "Hand")
                        .WithMany("BlackjackCards")
                        .HasForeignKey("HandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_BJCards_Hands");

                    b.Navigation("Hand");
                });

            modelBuilder.Entity("Chaos.Infraestructure.Models.BlackjackGameConfig", b =>
                {
                    b.HasOne("Chaos.Infraestructure.Models.Game", "Game")
                        .WithMany("BlackjackGameConfigs")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_BlackjackGameConfig_Games");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Chaos.Infraestructure.Models.BlackjackHand", b =>
                {
                    b.HasOne("Chaos.Infraestructure.Models.BlackjackSession", "BlackjackSession")
                        .WithMany("BlackjackHands")
                        .HasForeignKey("BlackjackSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_BJHands_Sessions");

                    b.Navigation("BlackjackSession");
                });

            modelBuilder.Entity("Chaos.Infraestructure.Models.BlackjackSession", b =>
                {
                    b.HasOne("Chaos.Infraestructure.Models.Animal", "Animal")
                        .WithMany("BlackjackSessions")
                        .HasForeignKey("AnimalId")
                        .IsRequired()
                        .HasConstraintName("FK_BJSessions_Animals");

                    b.HasOne("Chaos.Infraestructure.Models.BlackjackGameConfig", "BlackjackGameConfig")
                        .WithMany("BlackjackSessions")
                        .HasForeignKey("BlackjackGameConfigId")
                        .IsRequired()
                        .HasConstraintName("FK_BJSessions_GameConfig");

                    b.HasOne("Chaos.Infraestructure.Models.GameSession", "GameSession")
                        .WithMany("BlackjackSessions")
                        .HasForeignKey("GameSessionId")
                        .IsRequired()
                        .HasConstraintName("FK_BJSessions_GameSessions");

                    b.HasOne("Chaos.Infraestructure.Models.User", "User")
                        .WithMany("BlackjackSessions")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_BJSessions_Users");

                    b.Navigation("Animal");

                    b.Navigation("BlackjackGameConfig");

                    b.Navigation("GameSession");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Chaos.Infraestructure.Models.CoinFlipGameConfig", b =>
                {
                    b.HasOne("Chaos.Infraestructure.Models.Game", "Game")
                        .WithMany("CoinFlipGameConfigs")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CoinFlipGameConfig_Games");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Chaos.Infraestructure.Models.CoinFlipSession", b =>
                {
                    b.HasOne("Chaos.Infraestructure.Models.Animal", "Animal")
                        .WithMany("CoinFlipSessions")
                        .HasForeignKey("AnimalId")
                        .IsRequired()
                        .HasConstraintName("FK_CFSessions_Animals");

                    b.HasOne("Chaos.Infraestructure.Models.CoinFlipGameConfig", "CoinFlipGameConfig")
                        .WithMany("CoinFlipSessions")
                        .HasForeignKey("CoinFlipGameConfigId")
                        .IsRequired()
                        .HasConstraintName("FK_CFSessions_GameConfig");

                    b.HasOne("Chaos.Infraestructure.Models.GameSession", "GameSession")
                        .WithMany("CoinFlipSessions")
                        .HasForeignKey("GameSessionId")
                        .IsRequired()
                        .HasConstraintName("FK_CFSessions_GameSessions");

                    b.HasOne("Chaos.Infraestructure.Models.User", "User")
                        .WithMany("CoinFlipSessions")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_CFSessions_Users");

                    b.Navigation("Animal");

                    b.Navigation("CoinFlipGameConfig");

                    b.Navigation("GameSession");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Chaos.Infraestructure.Models.GameSession", b =>
                {
                    b.HasOne("Chaos.Infraestructure.Models.Animal", "Animal")
                        .WithMany("GameSessions")
                        .HasForeignKey("AnimalId")
                        .HasConstraintName("FK_GameSessions_Animals");

                    b.HasOne("Chaos.Infraestructure.Models.Game", "Game")
                        .WithMany("GameSessions")
                        .HasForeignKey("GameId")
                        .IsRequired()
                        .HasConstraintName("FK_GameSessions_Games");

                    b.HasOne("Chaos.Infraestructure.Models.User", "User")
                        .WithMany("GameSessions")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_GameSessions_Users");

                    b.Navigation("Animal");

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Chaos.Infraestructure.Models.HigherLowerGameConfig", b =>
                {
                    b.HasOne("Chaos.Infraestructure.Models.Game", "Game")
                        .WithMany("HigherLowerGameConfigs")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_HigherLowerGameConfig_Games");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Chaos.Infraestructure.Models.HigherLowerRound", b =>
                {
                    b.HasOne("Chaos.Infraestructure.Models.HigherLowerSession", "HigherLowerSession")
                        .WithMany("HigherLowerRounds")
                        .HasForeignKey("HigherLowerSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_HLRounds_HLSessions");

                    b.Navigation("HigherLowerSession");
                });

            modelBuilder.Entity("Chaos.Infraestructure.Models.HigherLowerSession", b =>
                {
                    b.HasOne("Chaos.Infraestructure.Models.Animal", "Animal")
                        .WithMany("HigherLowerSessions")
                        .HasForeignKey("AnimalId")
                        .IsRequired()
                        .HasConstraintName("FK_HLSessions_Animals");

                    b.HasOne("Chaos.Infraestructure.Models.GameSession", "GameSession")
                        .WithMany("HigherLowerSessions")
                        .HasForeignKey("GameSessionId")
                        .IsRequired()
                        .HasConstraintName("FK_HLSessions_GameSessions");

                    b.HasOne("Chaos.Infraestructure.Models.HigherLowerGameConfig", "HigherLowerGameConfig")
                        .WithMany("HigherLowerSessions")
                        .HasForeignKey("HigherLowerGameConfigId")
                        .IsRequired()
                        .HasConstraintName("FK_HLSessions_GameConfig");

                    b.HasOne("Chaos.Infraestructure.Models.User", "User")
                        .WithMany("HigherLowerSessions")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_HLSessions_Users");

                    b.Navigation("Animal");

                    b.Navigation("GameSession");

                    b.Navigation("HigherLowerGameConfig");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Chaos.Infraestructure.Models.RouletteBetType", b =>
                {
                    b.HasOne("Chaos.Infraestructure.Models.RouletteGameConfig", "RouletteGameConfig")
                        .WithMany("RouletteBetTypes")
                        .HasForeignKey("RouletteGameConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RouletteBetTypes_RouletteGameConfig");

                    b.Navigation("RouletteGameConfig");
                });

            modelBuilder.Entity("Chaos.Infraestructure.Models.RouletteGameConfig", b =>
                {
                    b.HasOne("Chaos.Infraestructure.Models.Game", "Game")
                        .WithMany("RouletteGameConfigs")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RouletteGameConfig_Games");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Chaos.Infraestructure.Models.RouletteSession", b =>
                {
                    b.HasOne("Chaos.Infraestructure.Models.GameSession", "GameSession")
                        .WithMany("RouletteSessions")
                        .HasForeignKey("GameSessionId")
                        .IsRequired()
                        .HasConstraintName("FK_RouletteSession_GameSession");

                    b.HasOne("Chaos.Infraestructure.Models.RouletteGameConfig", "RouletteGameConfig")
                        .WithMany("RouletteSessions")
                        .HasForeignKey("RouletteGameConfigId")
                        .IsRequired()
                        .HasConstraintName("FK_RouletteSession_RouletteGameConfig");

                    b.Navigation("GameSession");

                    b.Navigation("RouletteGameConfig");
                });

            modelBuilder.Entity("Chaos.Infraestructure.Models.RussianRouletteGameConfig", b =>
                {
                    b.HasOne("Chaos.Infraestructure.Models.Game", "Game")
                        .WithMany("RussianRouletteGameConfigs")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RussianRouletteGameConfig_Games");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Chaos.Infraestructure.Models.RussianRouletteLobby", b =>
                {
                    b.HasOne("Chaos.Infraestructure.Models.GameSession", "GameSession")
                        .WithMany("RussianRouletteLobbies")
                        .HasForeignKey("GameSessionId")
                        .HasConstraintName("FK_RussianRouletteLobbies_GameSessions");

                    b.HasOne("Chaos.Infraestructure.Models.RussianRouletteGameConfig", "RussianRouletteGameConfig")
                        .WithMany("RussianRouletteLobbies")
                        .HasForeignKey("RussianRouletteGameConfigId")
                        .IsRequired()
                        .HasConstraintName("FK_RRLobbies_GameConfig");

                    b.HasOne("Chaos.Infraestructure.Models.User", "Winner")
                        .WithMany("RussianRouletteLobbies")
                        .HasForeignKey("WinnerId")
                        .HasConstraintName("FK_RRLobbies_Winner");

                    b.Navigation("GameSession");

                    b.Navigation("RussianRouletteGameConfig");

                    b.Navigation("Winner");
                });

            modelBuilder.Entity("Chaos.Infraestructure.Models.RussianRoulettePlayer", b =>
                {
                    b.HasOne("Chaos.Infraestructure.Models.RussianRouletteLobby", "Lobby")
                        .WithMany("RussianRoulettePlayers")
                        .HasForeignKey("LobbyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RRPlayers_Lobbies");

                    b.HasOne("Chaos.Infraestructure.Models.User", "User")
                        .WithMany("RussianRoulettePlayers")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_RRPlayers_Users");

                    b.Navigation("Lobby");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Chaos.Infraestructure.Models.RussianRouletteRound", b =>
                {
                    b.HasOne("Chaos.Infraestructure.Models.RussianRouletteLobby", "Lobby")
                        .WithMany("RussianRouletteRounds")
                        .HasForeignKey("LobbyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RRRounds_Lobbies");

                    b.HasOne("Chaos.Infraestructure.Models.RussianRoulettePlayer", "Player")
                        .WithMany("RussianRouletteRounds")
                        .HasForeignKey("PlayerId")
                        .IsRequired()
                        .HasConstraintName("FK_RRRounds_Players");

                    b.Navigation("Lobby");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Chaos.Infraestructure.Models.ShopAnimalListing", b =>
                {
                    b.HasOne("Chaos.Infraestructure.Models.Animal", "Animal")
                        .WithMany("ShopAnimalListings")
                        .HasForeignKey("AnimalId")
                        .IsRequired()
                        .HasConstraintName("FK_Listings_Animals");

                    b.HasOne("Chaos.Infraestructure.Models.AnimalShop", "AnimalShop")
                        .WithMany("ShopAnimalListings")
                        .HasForeignKey("AnimalShopId")
                        .IsRequired()
                        .HasConstraintName("FK_Listings_AnimalShop");

                    b.Navigation("Animal");

                    b.Navigation("AnimalShop");
                });

            modelBuilder.Entity("Chaos.Infraestructure.Models.ShopTransaction", b =>
                {
                    b.HasOne("Chaos.Infraestructure.Models.Animal", "Animal")
                        .WithMany("ShopTransactions")
                        .HasForeignKey("AnimalId")
                        .IsRequired()
                        .HasConstraintName("FK_ShopTrans_Animals");

                    b.HasOne("Chaos.Infraestructure.Models.User", "User")
                        .WithMany("ShopTransactions")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_ShopTrans_Users");

                    b.Navigation("Animal");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Chaos.Infraestructure.Models.SlotGameConfig", b =>
                {
                    b.HasOne("Chaos.Infraestructure.Models.Game", "Game")
                        .WithMany("SlotGameConfigs")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SlotGameConfig_Games");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Chaos.Infraestructure.Models.SlotPayoutRule", b =>
                {
                    b.HasOne("Chaos.Infraestructure.Models.SlotGameConfig", "SlotGameConfig")
                        .WithMany("SlotPayoutRules")
                        .HasForeignKey("SlotGameConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PayoutRules_SlotGameConfig");

                    b.HasOne("Chaos.Infraestructure.Models.SlotSymbol", "SlotSymbol")
                        .WithMany("SlotPayoutRules")
                        .HasForeignKey("SlotSymbolId")
                        .IsRequired()
                        .HasConstraintName("FK_PayoutRules_SlotSymbols");

                    b.Navigation("SlotGameConfig");

                    b.Navigation("SlotSymbol");
                });

            modelBuilder.Entity("Chaos.Infraestructure.Models.SlotSession", b =>
                {
                    b.HasOne("Chaos.Infraestructure.Models.GameSession", "GameSession")
                        .WithMany("SlotSessions")
                        .HasForeignKey("GameSessionId")
                        .IsRequired()
                        .HasConstraintName("FK_SlotSession_GameSessions");

                    b.HasOne("Chaos.Infraestructure.Models.SlotGameConfig", "SlotGameConfig")
                        .WithMany("SlotSessions")
                        .HasForeignKey("SlotGameConfigId")
                        .IsRequired()
                        .HasConstraintName("FK_SlotSession_GameConfig");

                    b.Navigation("GameSession");

                    b.Navigation("SlotGameConfig");
                });

            modelBuilder.Entity("Chaos.Infraestructure.Models.SlotSymbol", b =>
                {
                    b.HasOne("Chaos.Infraestructure.Models.SlotGameConfig", "SlotGameConfig")
                        .WithMany("SlotSymbols")
                        .HasForeignKey("SlotGameConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SlotSymbols_SlotGameConfig");

                    b.Navigation("SlotGameConfig");
                });

            modelBuilder.Entity("Chaos.Infraestructure.Models.Animal", b =>
                {
                    b.Navigation("BlackjackSessions");

                    b.Navigation("CoinFlipSessions");

                    b.Navigation("GameSessions");

                    b.Navigation("HigherLowerSessions");

                    b.Navigation("ShopAnimalListings");

                    b.Navigation("ShopTransactions");
                });

            modelBuilder.Entity("Chaos.Infraestructure.Models.AnimalShop", b =>
                {
                    b.Navigation("ShopAnimalListings");
                });

            modelBuilder.Entity("Chaos.Infraestructure.Models.AnimalValueConfig", b =>
                {
                    b.Navigation("Animals");
                });

            modelBuilder.Entity("Chaos.Infraestructure.Models.BlackjackGameConfig", b =>
                {
                    b.Navigation("BlackjackSessions");
                });

            modelBuilder.Entity("Chaos.Infraestructure.Models.BlackjackHand", b =>
                {
                    b.Navigation("BlackjackActions");

                    b.Navigation("BlackjackCards");
                });

            modelBuilder.Entity("Chaos.Infraestructure.Models.BlackjackSession", b =>
                {
                    b.Navigation("BlackjackActions");

                    b.Navigation("BlackjackHands");
                });

            modelBuilder.Entity("Chaos.Infraestructure.Models.CoinFlipGameConfig", b =>
                {
                    b.Navigation("CoinFlipSessions");
                });

            modelBuilder.Entity("Chaos.Infraestructure.Models.Game", b =>
                {
                    b.Navigation("BlackjackGameConfigs");

                    b.Navigation("CoinFlipGameConfigs");

                    b.Navigation("GameSessions");

                    b.Navigation("HigherLowerGameConfigs");

                    b.Navigation("RouletteGameConfigs");

                    b.Navigation("RussianRouletteGameConfigs");

                    b.Navigation("SlotGameConfigs");
                });

            modelBuilder.Entity("Chaos.Infraestructure.Models.GameSession", b =>
                {
                    b.Navigation("BlackjackSessions");

                    b.Navigation("CoinFlipSessions");

                    b.Navigation("HigherLowerSessions");

                    b.Navigation("RouletteSessions");

                    b.Navigation("RussianRouletteLobbies");

                    b.Navigation("SlotSessions");
                });

            modelBuilder.Entity("Chaos.Infraestructure.Models.HigherLowerGameConfig", b =>
                {
                    b.Navigation("HigherLowerSessions");
                });

            modelBuilder.Entity("Chaos.Infraestructure.Models.HigherLowerSession", b =>
                {
                    b.Navigation("HigherLowerRounds");
                });

            modelBuilder.Entity("Chaos.Infraestructure.Models.RouletteGameConfig", b =>
                {
                    b.Navigation("RouletteBetTypes");

                    b.Navigation("RouletteSessions");
                });

            modelBuilder.Entity("Chaos.Infraestructure.Models.RussianRouletteGameConfig", b =>
                {
                    b.Navigation("RussianRouletteLobbies");
                });

            modelBuilder.Entity("Chaos.Infraestructure.Models.RussianRouletteLobby", b =>
                {
                    b.Navigation("RussianRoulettePlayers");

                    b.Navigation("RussianRouletteRounds");
                });

            modelBuilder.Entity("Chaos.Infraestructure.Models.RussianRoulettePlayer", b =>
                {
                    b.Navigation("RussianRouletteRounds");
                });

            modelBuilder.Entity("Chaos.Infraestructure.Models.SlotGameConfig", b =>
                {
                    b.Navigation("SlotPayoutRules");

                    b.Navigation("SlotSessions");

                    b.Navigation("SlotSymbols");
                });

            modelBuilder.Entity("Chaos.Infraestructure.Models.SlotSymbol", b =>
                {
                    b.Navigation("SlotPayoutRules");
                });

            modelBuilder.Entity("Chaos.Infraestructure.Models.User", b =>
                {
                    b.Navigation("AnimalValueConfigs");

                    b.Navigation("Animals");

                    b.Navigation("BlackjackSessions");

                    b.Navigation("CoinFlipSessions");

                    b.Navigation("GameSessions");

                    b.Navigation("HigherLowerSessions");

                    b.Navigation("RussianRouletteLobbies");

                    b.Navigation("RussianRoulettePlayers");

                    b.Navigation("ShopTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
